"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup
import glob

APP = ['launch.py']
#DATA_FILES = list(glob.glob('img/*.png'))+['img/kenvector_future_thin.ttf', "snd/dead.mp3"]
DATA_FILES = ['img', 'snd', 'levels']
OPTIONS = {'argv_emulation': True}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
